### ISSUE TITLE
Saved Templates: Odd scrollbar appearing

### ISSUE THREAD

**Issue by swissspidy** [google/web-stories-wp#9399]
## Bug Description

Even when you have only 1 saved page template or maybe 2 there's a scrollbar appearing in the page templates panel.

## Expected Behaviour

No scrollbar plz

## Steps to Reproduce

1. Open page templates tab
2. Save a custom page template if you don't have any yet
3. See scrollbar

## Screenshots

![Screenshot 2021-10-12 at 19 16 49](https://user-images.githubusercontent.com/841956/137124938-b3bb6c66-a646-4321-bde9-b41f58bad543.png)

## Additional Context

- Plugin Version: 1.13.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
cc @BrittanyIRL @miina not sure which pod is usually working on this area

**Comment by miina** [comment]
This specific tab (issue) would be for Prometheus.

**Comment by BrittanyIRL** [comment]
@miina this might actually get resolved with work pea pod is doing right now with the default templates + some discovery to swap out the saved templates to use the same html to image that you all introduced via the carousel. Can I take it for now?

**Comment by miina** [comment]
@BrittanyIRL Sure!

**Comment by csossi** [comment]
Scrollbar still appearing:
![image](https://user-images.githubusercontent.com/16945664/138335959-b7176006-974c-41b5-984b-d0f68d4d4c6b.png)

**Comment by swissspidy** [comment]
@samwhale @csossi looks like the PR build failed to upload for QA 🤔 Something that apparantly happens for multiple PRs today, as also noted by @miina. I‘ll need to look into this on Monday.

**Comment by swissspidy** [comment]
Meanwhile you can manually grab the ZIP file from the GitHub Actions output (see docs/ folder for instructions) to manually upload it to a WP site.

**Comment by samwhale** [comment]
I was just about to post this! Verified that the change didn't make it to qa. There should be a `height: 100%` on this element
![image](https://user-images.githubusercontent.com/22185279/138349511-160d1f45-1a9c-4045-86b7-d6fb94ca1db0.png)

**Comment by swissspidy** [comment]
The correct version should now be available again on the QA site, all relevant builds passed:
![Screenshot 2021-10-25 at 16 09 19](https://user-images.githubusercontent.com/841956/138711122-e5007efe-39e7-4efc-a293-864265b0fdc7.png)

**Comment by csossi** [comment]
Verified in QA
